### ISSUE TITLE
Connecting to MongoDB via localhost can fail in node.js v17 and above

### ISSUE THREAD

**Issue by toBeOfUse** [hacksu/khe-2023#8]
As described in [this Mongoose issue](https://github.com/Automattic/mongoose/issues/11250): depending on your operating system configuration, [in node v17 and above](https://github.com/nodejs/node/issues/40537), `localhost` can resolve to the IPv6 address `::1` instead of the usual IPv4 loopback address `127.0.0.1`, which kept me from being able to connect to the MongoDB server on my local device when running this project, because MongoDB needs to be started from the command line with a special flag before it will support IPv6 connections. The IPv4/IPv6 issue could be disambiguated by changing the URI in [projects/server/.env](https://github.com/hacksu/khe-2023/blob/main/projects/server/.env) from `localhost` to `127.0.0.1`.

**Comment by cseitz** [comment]
I've pushed this change to main!
